### ISSUE TITLE
Upgrade to Rails 4?

### ISSUE THREAD

**Issue by joevandyk** [adzap/grouped_validations#11]
Any chance this gem could be compatible with Rails 4?

**Comment by krancour** [comment]
Another github user named @peterbeers forked this and made it Rails 4 compatible.  It works great.  But neither this nor peterbeer's is Rails 4.1 compatible.  I dug down into this and try as I might, I couldn't get it to work with Rails 4.1.  If someone who understands validations (and the callbacks used internally by validations) better than me, I'd be very interested in a Rails 4.1-compatible version of this.

**Comment by marklohr** [comment]
Refer to the changes made to the gem here:  
https://github.com/BroiSatse/grouped_validations/commit/49f634a655391aade53870ab4e7091d6605c2208

This fixed the issue for us using Rails 4.2.4.

**Comment by umer98** [comment]
I am using Rails 4.2.4 but I am still getting the following error:

```
2.2.3 :002 > game.valid?
NoMethodError: undefined method `validate' for #<ActiveSupport::Callbacks::Callback:0x007f9ae41149b0>
```

Any ideas?
